# Generated by Django 3.0.5 on 2020-04-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subj1',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='subj2',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='subj3',
            field=models.FloatField(default=None),
        ),
    ]
