# Generated by Django 3.0.5 on 2020-05-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200422_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subj1_att',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subj2_att',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='subj3_att',
            field=models.FloatField(null=True),
        ),
    ]
