# Generated by Django 3.0.5 on 2020-05-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200509_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subj1_att',
            new_name='class_att_subj1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subj2_att',
            new_name='class_att_subj2',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subj3_att',
            new_name='class_att_subj3',
        ),
    ]
