# Generated by Django 3.0.5 on 2020-05-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200509_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.IntegerField(default=0)),
                ('subject2', models.IntegerField(default=0)),
                ('subject3', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='class_att_subj1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_att_subj2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_att_subj3',
            field=models.FloatField(default=0),
        ),
    ]
