# Generated by Django 3.0.5 on 2020-05-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200518_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class_taken',
        ),
    ]
