# Generated by Django 3.0.5 on 2020-05-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_delete_class_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_class_taken',
            field=models.IntegerField(default=0),
        ),
    ]
